// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Server;

public final class stringArrayHolder
{
    public
    stringArrayHolder()
    {
    }

    public
    stringArrayHolder(String[] value)
    {
        this.value = value;
    }

    public String[] value;
}
